spring:
  application.name: service-turbine
server:
  port: 8769

  # 1. cluster-name-expression指定集群名称，默认表达式appName；此时：turbine.app-config需要配置想要监控的应用名称
  # 2. 当cluster-name-expression: default时，turbine.aggregator.cluster-config可以不写，因为默认就是default
  # 3. 当cluster-name-expression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.cluster-config: ABC
turbine:
  combine-host-port: true
  app-config: eureka-ribbon-client,eureka-feign-client
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default
  instanceUrlSuffix: /hystrix.stream # 这里必须设置，否则默认程序会读取/actuator/hystrix.stream


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


