spring:
  application:
    name: test-fiegn

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: dev
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        instance-id:  ${spring.application.name}:${server.port}
        enabled: true
        service-name: ${spring.application.name}
        port: ${server.port}
        register: true

server:
  port: 3333

















